Wormhole integration
polkaswitch/polkaswitch-ui pull request #137
Opened 2022-03-08 20:56 UTC by IT-Prince

## Are you opening a new PR? Please fill the checlist below

[] Does the code work? Check whether function and logic are correct.
[] Are functions, methods, and variables adequately named?
[] Are names semantic and meaningful for your business?
[] Is it manually tested?
[] Is the code clear and easy to understand?
[] Is there any commented or unnecessary code? Try to avoid as much as possible, but if you let comments, explain WHY in the comment
[] Documentation needs to be updated?
[] Is the code as modular as possible?
[] Does the code consider failures? Is it just considering the happy path?
[] I have tested not only the happy path, but possible roots that can lead to code regression
[] Is there any performance issue?

2022-03-08 22:30 UTC, chillvybz commented
Tests are failing @IT-Prince

2022-03-08 22:31 UTC, chillvybz commented on package.json
> +    "@material-ui/core": "^4.12.2",
Can you move all these dependencies to the devDependencies? We only keep server-side dependencies in this area

2022-03-09 00:42 UTC, chillvybz commented on src/client/js/utils/wormhole.js
> +import _ from 'underscore';
This file looks completely Work-In-Progress.

2022-03-09 00:45 UTC, chillvybz commented on src/client/js/utils/nxtp.js
> +      if (e.chainId != '' + SOLANA_CHAIN_ID &&
can you do this instead: `if (+e.chainId !== SOLANA_CHAIN_ID &&`

2022-03-09 00:46 UTC, chillvybz commented on src/client/js/utils/eventEmitter.js
> +import { EventEmitter as Emitter } from 'eventemitter3';
What's this file for?

2022-03-09 00:57 UTC, chillvybz requested changes

2022-03-09 00:57 UTC, chillvybz commented on src/client/js/utils/eventEmitter.js
> +/* eslint-disable max-classes-per-file */
What's this entire file for?

2022-03-09 00:57 UTC, chillvybz commented on src/client/js/components/partials/TokenSearchBar.jsx
> +      const tokenAccount = getSolanaAccountByMint(token.address);
Is this method instant? no async or promise? Will it hold up the UI?

2022-03-09 07:41 UTC, IT-Prince commented on src/client/js/utils/wormhole.js
> +import _ from 'underscore';
Let me remove wormhole.js

2022-03-09 07:41 UTC, IT-Prince commented on src/client/js/utils/nxtp.js
> +      if (e.chainId != '' + SOLANA_CHAIN_ID &&
sure

2022-03-09 07:42 UTC, IT-Prince commented on src/client/js/utils/eventEmitter.js
> +/* eslint-disable max-classes-per-file */
this event is managed in the context of SolanaAccounts.jsx

2022-03-09 07:42 UTC, IT-Prince commented on src/client/js/components/partials/TokenSearchBar.jsx
> +      const tokenAccount = getSolanaAccountByMint(token.address);
it's not async
because all account infos are stored as global variable once we get using wallet

2022-03-09 08:00 UTC, yuripramos commented on package.json
> +    "node": ">=14.x",
Why change this line? I've tested our environment using node `16.4.2` and some deps wasn't working, to enable this we need to make sure there's no impact in the application. Since this PR is related to Solana I think there's no relation with node versions.

2022-03-09 08:03 UTC, yuripramos commented on src/client/js/utils/txBridgeManager.js
> +    console.log(supportedBridges);
according our PR checklist we have  _Is there any commented or unnecessary code? Try to avoid as much as possible, but if you let comments, explain WHY in the comment_ as one the required checks.

I don't see why the console.log is required here, so if it's not work in progress and there's no explanation for it, please remove it ✌️

2022-03-10 07:58 UTC, IT-Prince commented on package.json
> +    "@material-ui/core": "^4.12.2",
fixed dependency to devDependency

2022-03-10 22:21 UTC, yuripramos requested changes
I liked the code in general, congrats 🤖

Just minor stuff that needs to be improved and 3 other things:

1 - Please fill out the checklist that is being used to open the PR, don't need to follow it strictly but just give us some idea about what is being done in this PR. It is a big PR it will help us out.

2 - There are almost 6k+ lines of code, I would expect more commits. Since we still don't have e2e tests or unit tests yet to cover a good part of our application would be great to create smaller commits. With that, **we can inspect possible bugs better or even revert code more easier in case of necessity.**

3 - How can I reproduce this in my local environment? besides installing new deps, could you please briefly explain or at least take one screenshot?

2022-03-10 22:21 UTC, yuripramos commented on src/client/js/context/EthereumProviderContext.jsx
> +  const [providerError, setProviderError] = useState<string | null>(null);
Type definitions in `.jsx` not in `.tsx` files? I thought it worked only on typescript files 🤔

2022-03-10 22:21 UTC, yuripramos commented on src/client/js/context/SolanaConnection.jsx
> +export const sendTransaction = async (
another huge comment that I don't understand why is here, is this a TODO? undone work? garbage?

2022-03-10 22:21 UTC, yuripramos commented on src/client/js/utils/eventEmitter.js
> +/* eslint-disable max-classes-per-file */
we already have one file similar to that, at `polkaswitch-ui/src/client/js/utils/events.js`

Possible approaches: 
- Refactor the utils/events.js and add your solana events within it
- Rename `eventEmitter` to something more related to Solana to make it more semantic e.g. solanaEvents

2022-03-15 00:40 UTC, IT-Prince commented on src/client/js/utils/eventEmitter.js
> +/* eslint-disable max-classes-per-file */
moved all classes adding Sol prefix

2022-03-15 00:42 UTC, IT-Prince commented on public/tokens/sol.list.json
> +[
okay

2022-03-15 00:46 UTC, IT-Prince commented on src/client/js/components/App.jsx
> +import {SolanaConnectionProvider} from '../context/SolanaConnection';
okay

2022-03-15 01:14 UTC, IT-Prince commented on src/client/js/components/partials/KeyAndBalance.jsx
> +  // else if (chainId === 'terra') {
removed

2022-03-15 01:25 UTC, IT-Prince commented on src/client/js/context/EthereumProviderContext.jsx
> +  const [providerError, setProviderError] = useState<string | null>(null);
removed

2022-03-15 01:25 UTC, IT-Prince commented on src/client/js/utils/solanaUtils.js
> +export const WRAPPED_SOL_MINT = "So11111111111111111111111111111111111111112";
removed

2022-03-15 01:26 UTC, IT-Prince commented on src/client/js/context/SolanaConnection.jsx
> +export const sendTransaction = async (
removed

2022-03-15 15:44 UTC, yuripramos commented
I'm reviewing your code but still got failing tests, that in development is working properly.

have u ran the `yarn patch-google-proto` after `yarn` (or `npm install`)

2022-03-15 18:02 UTC, yuripramos requested changes
Almost there! 😀🚀

1 - Looks like the UI in the select wallet for Solana wallet is totally different than our UI. You can keep the different color (blue) but at least use the same border-radius, font, and sizes as the primary connect wallet button.

I don't know, maybe this "select wallet" can lead to some confusion to our users... maybe Sol wallet instead 🤔? Because we already have the connect wallet button. Any 💭on this
@8d526 @chillvybz ?

<img width="948" alt="image" src="https://user-images.githubusercontent.com/7452143/158439943-9ab4dd99-d7b6-4bd9-82ff-42d204b0200e.png">


2 - Is it expected to have the Solana Wallet only on the bridge tab? I cannot see the button within the single-chain swaps

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/7452143/158441233-0afa6e6d-0a5c-4194-ba89-8ce4fa601362.png">


3 - After connecting on the Solana Wallet I just can see the balance after refreshing the page or after handling the list of tokens. In the metamask I can see the balance for all the EVM tokens in the selected wallet.

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/7452143/158441721-5d6d2f46-f1ce-488d-877a-d7c478e0e15d.png">

2022-03-17 18:28 UTC, IT-Prince commented on src/client/js/utils/txBridgeManager.js
> +    console.log(supportedBridges);
Removed

2022-05-10 18:04 UTC, closed without merging