[FEATURE] crosschain-swap-api integration - `getQuotes` endpoint
polkaswitch/polkaswitch-ui pull request #151
Opened 2022-03-31 19:42 UTC by yuripramos

## Are you opening a new PR? Please fill the checklist below

[] Does the code work? Check whether function and logic are correct.
[x] Are functions, methods, and variables adequately named?
[x] Are names semantic and meaningful for your business?
[x] Is it manually tested?
[x] Is the code clear and easy to understand?
[] Is there any commented or unnecessary code? Try to avoid as much as possible, but if you let comments, explain WHY in the PR
[] Documentation needs to be updated?
[x] Is the code as modular as possible?
[] Does the code consider failures? Is it just considering the happy path?
[] I have tested not only the happy path, but possible roots that can lead to code regression
[] Is there any performance issue?

This PR is related only to **getQuote** endpoint with a few considerations:

1.  This solution has some temporary workarounds
2.  Usage of `temp/nxtp-yuri` branch instead of `main` to hit `crosschain-swap-api-web-frontend.dev.swing.xyz` endpoint to get specific nxtp response to make able to proceed further steps in the frontend without using `/transfer` and `/claim` endpoints yet
4. FIltering only cbridge and nxtp as supported networks during the process of migration because our frontend currently only supports these bridges so far. i.e. until we migrate the whole application I'm displaying only cbridge and nxtp as possible routes.

2022-04-11 17:45 UTC, chillvybz commented on src/client/js/utils/wallet.js
> +  returnEstimatedReturnAmountDeductedByFees: function (estimateTx) {
Tthis seems like useful logic to exist in the API itself.
cc @8d526

2022-04-11 17:45 UTC, chillvybz commented on src/client/js/utils/txBridgeManager.js
> +    return bridgeName === 'nxtp' || bridgeName === 'celer';
this should from from the API

2022-04-11 17:46 UTC, chillvybz commented on src/client/js/utils/txBridgeManager.js
> -    // TODO: Implement Hop TxHistory
is history integratoim from the API coming later?

2022-04-11 17:47 UTC, chillvybz commented on src/client/js/utils/cbridge.js
>  import { abi as BridgeABI } from '../../../contract/celer_contract/Bridge.json';
are these cbridge.js and nxtp.js files still relevant ? if it's abstracted away by the API?

2022-04-11 17:48 UTC, chillvybz commented on src/client/js/utils/requests/utils.js
> +const baseUrl = 'https://crosschain-swap-api-web-frontend.dev.swing.xyz';
should be an injected ENV_VAR from webpack

2022-04-11 20:17 UTC, chillvybz requested changes

2022-04-11 20:17 UTC, chillvybz commented on src/client/js/components/partials/bridge/BridgeWidget.jsx
> -    this.CROSS_CHAIN_NETWORKS.push(
why you delete?

2022-04-11 20:18 UTC, chillvybz commented
I re-read your PR comment and answers some of my questions but curious to hear more of your thoughts about some of the particular items.

2022-04-11 20:52 UTC, yuripramos commented on src/client/js/utils/txBridgeManager.js
> +    return bridgeName === 'nxtp' || bridgeName === 'celer';
This is temporary only for `getQuotes` only. Like I said in item No. 2 after we merge the entire process we need to make support only to the quotes that our FE supported before the API i.e. celer and nxtp 😄.

If we in the first step of the migration allow our users to choose any other bridge than the aforementioned we need to make support in our FE using their SDK, like we've done creating `utils/nxtp.js` and `utils/cbridge.js`

2022-04-11 20:52 UTC, yuripramos commented on src/client/js/utils/txBridgeManager.js
> -    // TODO: Implement Hop TxHistory
Yes. this PR is for getQuotes only

2022-05-03 19:07 UTC, chillvybz commented on src/client/js/components/partials/bridge/AvailableRoutes.jsx
> +        ?.filter((item) => item.bridgeType === 'nxtp' || item.bridgeType === 'celer')
??

2022-05-03 19:07 UTC, chillvybz commented on src/client/js/components/partials/bridge/BridgeWidget.jsx
> -    this.CROSS_CHAIN_NETWORKS.push(
??

2022-05-03 19:07 UTC, chillvybz commented on src/client/js/utils/requests/utils.js
> +const baseUrl = 'https://crosschain-swap-api-web-frontend.dev.swing.xyz';
??

2022-05-03 19:07 UTC, chillvybz commented on src/client/js/utils/cbridge.js
>  import { abi as BridgeABI } from '../../../contract/celer_contract/Bridge.json';
??

2022-05-04 02:50 UTC, closed without merging