[FEATURE] Cross-chain sendTransfer
polkaswitch/polkaswitch-ui pull request #158
Opened 2022-04-23 13:10 UTC by yuripramos

WIP!

## Are you opening a new PR? Please fill the checklist below

[] Does the code work? Check whether function and logic are correct.
[] Are functions, methods, and variables adequately named?
[] Are names semantic and meaningful for your business?
[] Is it manually tested?
[] Is the code clear and easy to understand?
[] Is there any commented or unnecessary code? Try to avoid as much as possible, but if you let comments, explain WHY in the PR
[] Documentation needs to be updated?
[] Is the code as modular as possible?
[] Does the code consider failures? Is it just considering the happy path?
[] I have tested not only the happy path, but possible roots that can lead to code regression
[] Is there any performance issue?

Dependant  from PR #151 - getQuotes

2022-05-02 18:18 UTC, chillvybz commented
how does this layer on top of the getQuotes PR?

2022-05-03 10:29 UTC, yuripramos commented
> how does this layer on top of the getQuotes PR?

I've just created a new branch from the getQuotes Branch

2022-05-03 19:11 UTC, chillvybz commented
I'm just going to review/comment this PR only instead of the getQuotes then.
A more traditional way is for you to target the PRs to each other linearly. but this requires no re-basing, which you seem to do alot, because that wipes/resets git history and you get a bunch of conflicts.
You want to keep the git tree consistent when doing multiple branches.

I'm just going to close the other PR.

Another thing is: If this PR in it's current state can't stand alone (i.e can't merge into development yet), and you have more substantial work that needs to still be done to fully complete this, then we should have a new target branch.

2022-05-04 03:01 UTC, yuripramos commented
@chillvybz answering your question in the closed PR: 

**are these cbridge.js and nxtp.js files still relevant? if it's abstracted away by the API?**

Yes, because we still have the finish/claim for nxtp on modal and the refund for celer in the modal. It will be deleted soon when our API support the refund policy for celer.

2022-05-04 16:18 UTC, chillvybz requested changes
🚀 big one!
Looks good for the most part.
Needs more battle-testing for sure.

2022-05-04 16:18 UTC, chillvybz commented on src/client/js/components/partials/bridge/BridgeWidget.jsx
> +      toChainNetworkChange,
is this right? I think we want to key these properly with (to, from, toChain, fromChain).

2022-05-04 16:18 UTC, chillvybz commented on src/client/js/components/partials/bridge/BridgeWidget.jsx
> +    setShowSearch(false);
`// make it easy coming from token-selection`
try to keep the original comments. it's intended to point out non-obvious reasons for certain lines of code.

2022-05-04 16:18 UTC, chillvybz commented on src/client/js/components/partials/bridge/BridgeWidget.jsx
> +    if (parseInt(fromAmount) > parseInt(allowanceFormatted)) {
so how is the alternate case handled where we need to call approve()

2022-05-04 16:18 UTC, chillvybz commented on src/client/js/components/partials/bridge/CrossSwapProcessSlide.jsx
> +      case this.props.isAllowanceToken:
`isAllowanceToken` i understand the use-case case but the term isAllowanceToken seems misleading/confusing. It's more so "requiresTokenApproval"

2022-05-04 16:18 UTC, chillvybz commented on src/client/js/components/partials/bridge/CrossSwapProcessSlide.jsx
> +  //future deprecated
let's delete, if old code

2022-05-04 16:18 UTC, chillvybz commented on src/client/js/utils/txBridgeManager.js
> +      `${baseUrl}/v0/transfer/allowance?tokenSymbol=${symbol}&tokenAddress=${address}&bridge=${bridge}&fromChain=${fromChain}&fromChainId=${chainId}&fromAddress=${fromAddress}`,
this is a little unsafe to build a query param like this, can you use a helper function like this:


```
/**
 * Encode an object as url query string parameters
 * - includes the leading "?" prefix
 * - example input — {key: "value", alpha: "beta"}
 * - example output — output "?key=value&alpha=beta"
 * - returns empty string when given an empty object
 */
function encodeQueryString(params) {
    const keys = Object.keys(params)
    return keys.length
        ? "?" + keys
            .map(key => encodeURIComponent(key)
                + "=" + encodeURIComponent(params[key]))
            .join("&")
        : ""
}

encodeQueryString({key: "value", alpha: "beta"})
 //> "?key=value&alpha=beta"
```

2022-05-04 16:18 UTC, chillvybz commented on src/client/js/utils/txBridgeManager.js
> +      `${baseUrl}/v0/transfer/status?userAddress=${userAddress}&txId=${id}&bridge=${bridge}&fromChain=${fromChainName}&fromChainId=${fromChainId}&toChainId=${toChainId}
see note about query params

2022-05-04 16:18 UTC, chillvybz commented on src/client/js/utils/txBridgeManager.js
> +      `${baseUrl}/v0/transfer/approve?tokenSymbol=${symbol}&tokenAddress=${address}&bridge=${bridge}&fromChain=${fromChainName}&fromChainId=${fromChainId}&toChainId=${toChainId}
see not about query params

2022-05-04 16:19 UTC, chillvybz commented
Also careful with the force-pushing and re-baseing because Github comments get confused and loses original markers in the code.

2022-05-04 16:51 UTC, yuripramos commented on src/client/js/utils/txBridgeManager.js
> +      `${baseUrl}/v0/transfer/allowance?tokenSymbol=${symbol}&tokenAddress=${address}&bridge=${bridge}&fromChain=${fromChain}&fromChainId=${chainId}&fromAddress=${fromAddress}`,
amazing function, will add it now, thanks

2022-05-04 17:35 UTC, yuripramos commented on src/client/js/components/partials/bridge/AvailableRoutes.jsx
> -      route = route.concat([
chuqiao said that this logic would be updated in the next UI, from now only details from and to.

2022-05-04 17:35 UTC, yuripramos commented on src/client/js/components/partials/bridge/BridgeWidget.jsx
> +    if (parseInt(fromAmount) > parseInt(allowanceFormatted)) {
In my understanding, this is the only one. In this case, we start the transfer without calling allowance.

2022-05-04 18:28 UTC, yuripramos commented on src/client/js/components/partials/TokenSearchSlide.jsx
> +            handleClose={() => this.props.handleSearchToggle('to')} // "to" is arbitary
it's not being used on `src/client/js/components/partials/swap/SwapWidget.jsx`, I've just checked

2022-05-04 18:33 UTC, yuripramos commented on src/client/js/components/partials/bridge/BridgeWidget.jsx
> +      toChainNetworkChange,
I've just renamed it... because `to, from, toChain and fromChain` values were already defined, in the useState

2022-05-04 20:32 UTC, chillvybz commented on src/client/js/components/partials/bridge/BridgeWidget.jsx
> +      toChainNetworkChange,
to i mean the keys in the param of this function is important no?

We want something like this:
```
to: toChainNetworkChange,
from: fromChainNetworkChange,
toChain: toNetworkChange
fromChain: fromNetworkChange,
```

2022-05-04 20:33 UTC, chillvybz commented on src/client/js/components/partials/TokenSearchSlide.jsx
> +            handleClose={() => this.props.handleSearchToggle('to')} // "to" is arbitary
yea it is:
https://github.com/polkaswitch/polkaswitch-ui/blob/feature/cross-chain-api-sendTransfer/src/client/js/components/partials/swap/SwapWidget.jsx#L239-L251

2022-05-05 06:12 UTC, yuripramos commented on src/client/js/components/partials/TokenSearchSlide.jsx
> +            handleClose={() => this.props.handleSearchToggle('to')} // "to" is arbitary
Ok, updated `TokenSearchSlide` within `SwapWidget`

before: 
handleSearchToggle={this.handleSearchToggle}

after: 
handleSearchToggle={() => this.handleSearchToggle}

2022-05-05 20:10 UTC, chillvybz commented
Okay I assume you didn't make any other changes other than the PR feedback because the force-push makes it hard to see what the new material changes are without reviewing entire PR again.

But things good now.

2022-05-05 20:10 UTC, chillvybz approved these changes

2022-05-05 20:11 UTC, chillvybz commented
Okay so I guess we are ready to merge this.

@8d526 this is going to alpha so alpha may be unstable for a bit. we will get more testers on it.

2022-05-05 20:11 UTC, merged