fix issue (Transaction History is not preserved on Browser Refresh #9)
polkaswitch/polkaswitch-ui pull request #17
Opened 2021-07-02 16:18 UTC by davidkoller318

Hi, Chuqiao
I fixed issue. 

Please review it. 
Best Regards
David Koller

2021-07-06 19:33 UTC, chillvybz requested changes
Looks good for the most part. Minor comments.

2021-07-06 19:33 UTC, chillvybz commented on src/client/js/utils/txQueue.js
> +    store.set(this._signerAddress, this._queue)
Let's make sure signerAddress is set vs unset before storing the Queue.

2021-07-06 19:33 UTC, chillvybz commented on src/client/js/utils/txQueue.js
> +    const queue = store.get(this._signerAddress) ? store.get(this._signerAddress) : {};
Minor but let's cache the `store.get(this._signerAddress)` return value instead of requesting it twice.
it's a performance hit to serialize and de-serialize.

2021-07-06 19:33 UTC, chillvybz commented on src/client/js/utils/txQueue.js
> +    this._signerAddress = Wallet.currentAddress()
I like that you scoped the queue by address - which is good.

2021-07-07 02:17 UTC, softskillpro commented on src/client/js/utils/txQueue.js
> +    store.set(this._signerAddress, this._queue)
>> Let's make sure signerAddress is set vs unset before storing the Queue.
if signerAddress is undefined or length is 0,  we shouldn't store. right?

2021-07-07 02:43 UTC, chillvybz commented on src/client/js/utils/txQueue.js
> +    store.set(this._signerAddress, this._queue)
Correct

2021-07-07 03:36 UTC, davidkoller318 commented
Hi, @chillvybz 
I fixed issue. 
Please review . Thank you

2021-07-08 16:24 UTC, chillvybz commented on src/client/js/utils/txQueue.js
> +    const queue = store.get(this._signerAddress);
do this:
`const queue = store.get(this._signerAddress) || {}`

2021-07-08 16:25 UTC, chillvybz commented on src/client/js/utils/txQueue.js
> +    if (this._signerAddress && (this._signerAddress.length > 0)) {
Don't wrap the `data.tx.wait` in this IF.
Only the following 2 lines up to LN 28.

2021-07-08 16:34 UTC, davidkoller318 commented on src/client/js/utils/txQueue.js
> +    const queue = store.get(this._signerAddress);
Okay

2021-07-08 19:48 UTC, chillvybz approved these changes

2021-07-08 19:48 UTC, merged