Trading View Demo
polkaswitch/polkaswitch-ui pull request #41
Opened 2021-08-27 19:38 UTC by davidsoft318

Hi, @chillvybz 

Please check trading view demo
Thank you.

2021-08-30 16:33 UTC, chillvybz commented on public/config/main.config.json
> +      "from": "0x0000000000000000000000000000000000001010"
Any reason you had to change this address?

2021-08-30 16:49 UTC, davidkoller318 commented on public/config/main.config.json
> +      "from": "0x0000000000000000000000000000000000001010"
@chillvybz 
MATIC contract address is 0x0000000000000000000000000000000000001010 in Polygonscan.
When fetch the price info from coingecko api, we should send the exact contract address as a param. 

This address should be 0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE ?

2021-08-30 17:46 UTC, davidkoller318 commented on public/config/main.config.json
> +      "from": "0x0000000000000000000000000000000000001010"
Do we have any problems?

2021-08-30 23:52 UTC, chillvybz requested changes

2021-08-30 23:52 UTC, chillvybz commented on src/client/js/components/partials/swap/TradingViewChart.jsx
> +  const wrapTokens = {
why are these hard-coded?

2021-08-30 23:52 UTC, chillvybz commented on src/client/js/utils/tokenList.js
> +    window.SELECTED_NETWORK = network.name;
you can remove this line. I think bad conflict here. I moved logic to `Storage.updateNetwork`

2021-08-30 23:52 UTC, chillvybz commented on src/client/js/index.js
> +window.COINGECKO_TOKEN_LIST = await(await fetch('/tokens/coingecko.list.json')).json();
How does the coingecko list diff from our list?

2021-08-30 23:52 UTC, chillvybz commented on src/client/js/index.js
> +window.COINGECKO_TOKEN_LIST = await(await fetch('/tokens/coingecko.list.json')).json();
Also where is this file? I don't see it here

2021-08-30 23:52 UTC, chillvybz commented on src/client/js/utils/tokenList.js
> +  updateSwapConfig: function(swap) {
I understand why you introduced this "swap config".
But seems poorly introduced.

If I understand correctly, the goals are:
1) Updating the token in the SwapWidget should update the Pair in the TradingChart to display
2) Switching network, should update the SwapWidget and the TradingChart
3) Make any changes in TradingChat (if possible), should also switch SwapWidget pair
4) Future components include the GlobalSearchBar across the top, which should update both SwapWidget and TradingChart simultaneously.

Basically, the TradingChart and SwapWidget should display the same Pair.

I think this TokenList utility file could take on a larger role of managing:
- current network
- token list
- focused pair on the dashboard

2021-08-31 01:59 UTC, davidkoller318 commented on src/client/js/index.js
> +window.COINGECKO_TOKEN_LIST = await(await fetch('/tokens/coingecko.list.json')).json();
Sorry, I pushed it.

2021-08-31 14:41 UTC, davidkoller318 commented on src/client/js/components/partials/swap/TradingViewChart.jsx
> +  const wrapTokens = {
you mean wrapToken?

const wrapTokens = {
    "BNB": "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c",
    "AVAX": "0xB31f66AA3C1e785363F0875A1B74E27b85FD66c7"
  }

As you know, when fetch the price info from Coingecko service, we should send the contract address as a param.
Coingecko api doesn't support BNB, AVAX contract address for fetching price. 
It support WBNB instead of BNB,  WAVAX instead of AVAX.

2021-08-31 14:43 UTC, davidkoller318 commented on src/client/js/utils/tokenList.js
> +    window.SELECTED_NETWORK = network.name;
Okay. removed.

2021-08-31 14:55 UTC, davidkoller318 commented on src/client/js/utils/tokenList.js
> +  updateSwapConfig: function(swap) {
1. Updating the token in the SwapWidget should update the Pair in the TradingChart to display. (Correct. it works like that)
2. Switching network, should update the SwapWidget and the TradingChart(Correct. it works like that)
3. Make any changes in TradingChat (if possible), should also switch SwapWidget pair
I referenced many popular dex site like  1inch, Paraswap, Uniswap etc. 
But  When make any changes in TradingChat ,  it doesn't switch swapWidget. 
For example, When token pair is BNB, USDC.   TradingChart displays 4 price charts.  BNB/USDC,  USDC/BNB, BNB, USDC. 
I hope you to run the trading view demo on local.
Thank you.

4. Future components include the GlobalSearchBar across the top, which should update both SwapWidget and TradingChart simultaneously. (Correct. it works like that)

2021-08-31 14:56 UTC, davidkoller318 commented on src/client/js/utils/tokenList.js
> +  updateSwapConfig: function(swap) {
Let's discuss about  this in detail.

2021-08-31 17:08 UTC, chillvybz commented
Issues:

1) Please fix this warning:
![image](https://user-images.githubusercontent.com/85249140/131546002-59e24728-bff2-43a5-ba9d-f91e3eeb9b1e.png)

2) Spacing between the columns is off. Really big in the middle between SwapWidget and TradingChart. Also there is a gap on the right side of the SwapWidget that doesn't align with the NavBar
![image](https://user-images.githubusercontent.com/85249140/131546174-a8434e74-6f70-4847-bc75-5727e78923e8.png)

3) Somthing happeneded to the SWAP func. Pricing not working:
![image](https://user-images.githubusercontent.com/85249140/131546221-9159f058-fab4-4f38-9326-d1f0234d9d70.png)

2021-08-31 17:11 UTC, davidkoller318 commented
Okay. got it.

2021-08-31 20:54 UTC, davidkoller318 commented
Hi, @chillvybz 
I fixed the issues.

2021-09-02 18:40 UTC, chillvybz commented
Still looking for the following updates:
-  loading view when fetching the price on trading view.
-  if there is no price data, Display “We are unable to fetch the data for the selected pair”

2021-09-04 08:41 UTC, davidkoller318 commented
> Still looking for the following updates:
> 
> * loading view when fetching the price on trading view.
> * if there is no price data, Display “We are unable to fetch the data for the selected pair”

Hi, @chillvybz 
I updated above task.
Please review it. 
Thank you

2021-09-24 20:59 UTC, chillvybz commented
![image](https://user-images.githubusercontent.com/85249140/134739047-020e45a0-578b-4303-b4ce-c9a57f8f558f.png)

It doesn't seem to scale well when the browser window re-sized

2021-09-24 21:02 UTC, chillvybz commented on src/client/js/index.js
> +window.COINGECKO_TOKEN_LIST = await(await fetch('/tokens/coingecko.list.json')).json();
Can you put this instructions as a code comment?
It is good documentation.

2021-09-24 21:03 UTC, chillvybz commented
This looks good outside of the browser resize issue.
The only other thing is related to how we should handle the global state for the current PAIR we are looking at. This comment here:
 https://github.com/polkaswitch/polkaswitch-ui/pull/41#discussion_r699408490

We can talk about this in a meeting.

2021-09-27 14:46 UTC, chillvybz commented
Closing. merged into #52

2021-09-27 14:46 UTC, closed without merging